name: Test Job
on:
  workflow_call:
      inputs:
        repository:
          required: false
          description: Select TA
          type: string
jobs:
  super-job:
    runs-on: ubuntu-22.04
    env: ${{ fromJSON(secrets.SUPERSECRET) }}
    steps:
      - name: Check secret
        shell: bash 
        run: |
          env
          echo " END OF ENV"
          echo "GCP_SERVICE_ACC_JSON $GCP_SERVICE_ACC_JSON"
          echo "GCP_CREDS_PATH: $GCP_CREDS_PATH" 
