on:
  workflow_dispatch:

jobs:
  # chekc-secrets:
  #   runs-on: ubuntu-22.04
  #   env:
  #     GH_TOKEN: ${{ github.token }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: |
  #         gh auth refresh
  #         gh secret list -a

  pass-secrets-to-workflow:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/job.yaml
    secrets: inherit